from enum import Enum


class State(str, Enum):
    QUESTION_REQUIRED = "QUESTION_REQUIRED",
    QUESTION_DISPLAYED = "QUESTION_DISPLAYED",
    ANSWER_DISPLAYED = "ANSWER_DISPLAYED",
    STATISTICS_SHOWN = "STATISTICS_SHOWN",
    EXITING = "EXITING"